services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cooking_book
      POSTGRES_USER: cooking_book
      POSTGRES_PASSWORD: cooking_book
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      COOKING_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      COOKING_CORE_SETTING_LOCAL_SETTINGS_PATH: 'core/project/settings.py'

volumes:
  postgresql-data:
    driver: local
